# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      if [ -z "${CONNECT_SERVER}" ] ; then
          echo "The CONNECT_SERVER environment variable is not defined. It defines"
          echo "the base URL of your RStudio Connect instance."
          echo 
          echo "    export CONNECT_SERVER='http://connect.company.com/'"
          exit 1
      fi
